"""updated spots table

Revision ID: f0f68448b41c
Revises: 2843224166c6
Create Date: 2021-02-21 12:36:37.446435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f68448b41c'
down_revision = '2843224166c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('zipcode', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'zipcode')
    # ### end Alembic commands ###
