"""empty message

Revision ID: 3430e93927f7
Revises: 397ca62cc8d1
Create Date: 2021-02-21 13:37:50.422905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3430e93927f7'
down_revision = '397ca62cc8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spots_id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['spots_id'], ['spots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundings')
    # ### end Alembic commands ###
