"""create_spots_table

Revision ID: 2843224166c6
Revises: ffdc0a98111c
Create Date: 2021-02-20 13:48:06.306597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2843224166c6'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('image_url', sa.String(
                        length=20083), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('address', sa.String(length=50), nullable=False),
                    sa.Column('city', sa.String(length=50), nullable=False),
                    sa.Column('state', sa.String(length=2), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=False),
                    sa.Column('capacity', sa.Integer(), nullable=False),
                    sa.Column('availability', sa.Integer(), nullable=False),
                    sa.Column('host_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spots')
    # ### end Alembic commands ###
