"""empty message

Revision ID: a92ee759c9c8
Revises: 3430e93927f7
Create Date: 2021-02-25 16:35:46.983791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92ee759c9c8'
down_revision = '3430e93927f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('spots', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'longitude')
    op.drop_column('spots', 'latitude')
    # ### end Alembic commands ###
